### ISSUE TITLE
When will you release the code and checkpoint file?

### ISSUE THREAD

**Issue by Xin-Zh00** [samar-khanna/DiffusionSat#1]

**Comment by samar-khanna** [comment]
It's taken a bit longer than I expected due to some server issues. I'm actively working on preparing it, please stay tuned!

**Comment by samar-khanna** [comment]
Hi, I've pushed the initial version of the code, which should support single-image generation using checkpoints!

**Comment by samar-khanna** [comment]
Single-image training is now uploaded. Working on conditional training scripts.

**Comment by samar-khanna** [comment]
Conditional training scripts are added!
