### ISSUE TITLE
Question about CFG during training

### ISSUE THREAD

**Issue by mikelmh025** [samar-khanna/DiffusionSat#12]
Dear authors, 

Wonderful paper and model code! It works really really good! I have question about zero out the meta data during training. If I have read your code in the correctly, only the meta data go zero out, but the text prompt. I believe that's a design choice from your experiment runs. Would you mind sharing some thoughts about this? 

[train_text_to_image.py](https://github.com/samar-khanna/DiffusionSat/blob/main/train_text_to_image.py#L935C17-L936C121) Line 935

`keep_mask = torch.rand_like(metadata) > 0.1`
`metadata = metadata * keep_mask + 0. * ~keep_mask * torch.ones_like(metadata)  # set drop metadata to -1`

Regards,
Minghao Liu

**Comment by samar-khanna** [comment]
Thanks! If you don't want to use text, you can pass a generic caption like "a satellite image" (figure 3 in the main paper)

**Comment by mikelmh025** [comment]
Thanks!

In my case, I will have some sort of **text prompts and metadata**. Should I zero out both of them like 10% of the time? Or I don't need to deal with the language part as what you did?

**Comment by samar-khanna** [comment]
If you see [this line](https://github.com/samar-khanna/DiffusionSat/blob/b6a1f558d93950d84d62a9a6392a830e6a735b0f/diffusionsat/data_util.py#L31), when constructing the caption, it would drop random pieces of it 10% of the time. You can use the same strategy for your case if you want the final model to be robust to generic captions.

**Comment by mikelmh025** [comment]
Thank! That helps a lot. I will also have some sort of template + real text.
