### ISSUE TITLE
Hi, I'm happy to see your work uploaded here, it's very colorful. 

### ISSUE THREAD

**Issue by gangtieyang** [samar-khanna/DiffusionSat#2]
Hi, I'm happy to see your work uploaded here, it's very colorful. Now I have a question for you, please tell me how to do the image generation if I want to use your checkpoint without joining metadata.

**Comment by samar-khanna** [comment]
Thank you! 

You can set those metadata items to 0.

(Note that this is a slight bug in how we trained it, and so future trained models might fix this. The correct way to handle missing metadata is to set the _embedded_ metadata to 0, but in the training of our checkpoints, we just set the actual metadata _value_ to 0, before passing it through the projection + embedding).

**Comment by gangtieyang** [comment]
> 谢谢！
> 
> 您可以将这些元数据项设置为 0。
> 
> （请注意，这是我们训练方式中的一个小错误，因此未来训练的模型可能会解决这个问题。处理缺失元数据的正确方法是将_嵌入_的元数据设置为 0，但在检查点的训练中，我们只需将实际元数据_值_设置为 0，然后再通过投影 + 嵌入）。

Thank you for your reply.
Do you mean to set all seven values of metadata to 0?

**Comment by samar-khanna** [comment]
Yes you can try that.

**Comment by gangtieyang** [comment]
All right, thanks for the help.
