### ISSUE TITLE
The part of Conditional Image Generation and Training

### ISSUE THREAD

**Issue by MLS2021** [samar-khanna/DiffusionSat#6]
Thank you for your excellent work and I would like to ask when the part of Conditional Image Generation and Training will be made public?

**Comment by haaaappy** [comment]
Maybe we can edit a code to use the conditional image generation, you can see the code files and there are some classes for conditional image generation I think.

**Comment by samar-khanna** [comment]
Closing this issue as I will be posting updates to this issue: https://github.com/samar-khanna/DiffusionSat/issues/1
