### ISSUE TITLE
What's your input in the pipe() when doing image inpainting and temporal generation?

### ISSUE THREAD

**Issue by haaaappy** [samar-khanna/DiffusionSat#8]
Thanks you for the excellent work! What's your input in the pipe() when doing image inpainting and temporal generation? How many images as the condition and how many prompts? And how to use the 【cond_metadata】 to control the class DiffusionSatControlNetPipeline? Can you explain each parameter in the class DiffusionSatControlNetPipeline? Thanks!

**Comment by samar-khanna** [comment]
Hey, please check `notebooks/controlnet_texas_samples.ipynb` for an example of this, it should give you a demonstration of how to generate samples for the ControlNet models. Note that this notebook is for the 3D ControlNet. The case for ControlNet that accepts a single conditioning image + conditioning metadata is similar.
